/* SPDX-License-Identifier: GPL-3.0-only */
/* libobsbot - cross-platform OBSBOT camera SDK
 * Generated by cbindgen. Do not edit by hand. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define OBSBOT_OK 0

/**
 * Generic / USB error.
 */
#define OBSBOT_ERR_USB -1

/**
 * No matching device.
 */
#define OBSBOT_ERR_NOT_FOUND -2

/**
 * Timeout while waiting for a camera response.
 */
#define OBSBOT_ERR_TIMEOUT -3

/**
 * Operation unsupported on this platform or device.
 */
#define OBSBOT_ERR_UNSUPPORTED -4

/**
 * Argument out of accepted range.
 */
#define OBSBOT_ERR_OUT_OF_RANGE -5

/**
 * Camera firmware too old.
 */
#define OBSBOT_ERR_FIRMWARE -6

/**
 * Camera returned a malformed response.
 */
#define OBSBOT_ERR_BAD_RESPONSE -7

/**
 * Event kind delivered by [`obsbot_devices_poll_event`].
 */
#define OBSBOT_EVENT_DEVICE_ADDED 1

/**
 * See [`OBSBOT_EVENT_DEVICE_ADDED`].
 */
#define OBSBOT_EVENT_DEVICE_REMOVED 2

/**
 * See [`OBSBOT_EVENT_DEVICE_ADDED`].
 */
#define OBSBOT_EVENT_STATUS 3

/**
 * Maximum string length (including NUL) for [`ObsbotStatus`] fields.
 */
#define OBSBOT_STR_MAX 64

/**
 * Opaque handle to an opened OBSBOT camera.
 */
typedef struct ObsbotDevice ObsbotDevice;

/**
 * Opaque handle to the hot-plug watcher / device registry.
 */
typedef struct ObsbotDevices ObsbotDevices;

/**
 * Plain-old-data form of [`libobsbot_core::Status`] for C consumers.
 * `firmware` and `serial` are NUL-terminated; strings longer than
 * `OBSBOT_STR_MAX - 1` bytes are truncated. The unused tail is
 * zero-padded.
 */
typedef struct ObsbotStatus {
  /**
   * Camera-reported firmware version, e.g. "4.4.6.1". NUL-terminated.
   */
  char firmware[OBSBOT_STR_MAX];
  /**
   * Camera-reported serial number. NUL-terminated.
   */
  char serial[OBSBOT_STR_MAX];
  /**
   * Brightness reported by the Processing Unit.
   */
  int32_t brightness;
  /**
   * Contrast reported by the Processing Unit.
   */
  int32_t contrast;
  /**
   * Saturation reported by the Processing Unit.
   */
  int32_t saturation;
  /**
   * Current zoom value (raw u16 cast to f32 for now).
   */
  float zoom;
  /**
   * Normalised pan in -1.0..=1.0.
   */
  float pan;
  /**
   * Normalised tilt in -1.0..=1.0.
   */
  float tilt;
} ObsbotStatus;

/**
 * One event delivered by [`obsbot_devices_poll_event`]. For Added /
 * Removed events the `status` fields are zeroed; for Status events
 * every field is filled exactly as in
 * [`obsbot_device_status`].
 */
typedef struct ObsbotEvent {
  /**
   * One of the `OBSBOT_EVENT_*` constants.
   */
  int kind;
  /**
   * Camera serial associated with the event. NUL-terminated.
   */
  char serial[OBSBOT_STR_MAX];
  /**
   * For Status events: the status snapshot. Zeroed otherwise.
   */
  struct ObsbotStatus status;
} ObsbotEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new `ObsbotDevices` registry. Returns NULL on failure.
 */
struct ObsbotDevices *obsbot_devices_new(void);

/**
 * Free an `ObsbotDevices` registry previously returned by
 * [`obsbot_devices_new`]. Passing NULL is a no-op.
 */
void obsbot_devices_free(struct ObsbotDevices *handle);

/**
 * Number of OBSBOT cameras currently connected.
 */
int obsbot_devices_count(struct ObsbotDevices *handle);

/**
 * Open the first connected OBSBOT camera. Writes the resulting handle to
 * `*out_device`. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_devices_open_first(struct ObsbotDevices *handle, struct ObsbotDevice **out_device);

/**
 * Pull the next event off the registry's queue. `timeout_ms` < 0
 * blocks indefinitely, 0 returns immediately if nothing is ready,
 * > 0 waits up to that many milliseconds.
 *
 * Returns `OBSBOT_OK` on success, `OBSBOT_ERR_TIMEOUT` when no event
 * arrived within `timeout_ms`, and `OBSBOT_ERR_NOT_FOUND` for invalid
 * arguments or a closed channel.
 */
int obsbot_devices_poll_event(struct ObsbotDevices *handle,
                              struct ObsbotEvent *out_event,
                              int32_t timeout_ms);

/**
 * Free an `ObsbotDevice` previously returned by [`obsbot_devices_open_first`].
 * Passing NULL is a no-op.
 */
void obsbot_device_close(struct ObsbotDevice *handle);

/**
 * Set camera brightness. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_device_set_brightness(struct ObsbotDevice *handle, int32_t value);

/**
 * Read camera brightness into `*out_value`.
 */
int obsbot_device_brightness(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set camera contrast. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_device_set_contrast(struct ObsbotDevice *handle, int32_t value);

/**
 * Read camera contrast into `*out_value`.
 */
int obsbot_device_contrast(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set camera saturation. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_device_set_saturation(struct ObsbotDevice *handle, int32_t value);

/**
 * Read camera saturation into `*out_value`.
 */
int obsbot_device_saturation(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set image hue (PU). i16 LE on the wire; out-of-range values
 * return `OBSBOT_ERR_OUT_OF_RANGE`.
 */
int obsbot_device_set_hue(struct ObsbotDevice *handle, int32_t value);

/**
 * Read current image hue into `*out_value`.
 */
int obsbot_device_hue(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set image sharpness (PU). u16 LE.
 */
int obsbot_device_set_sharpness(struct ObsbotDevice *handle, int32_t value);

/**
 * Read current image sharpness into `*out_value`.
 */
int obsbot_device_sharpness(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set sensor gain (PU). u16 LE.
 */
int obsbot_device_set_gain(struct ObsbotDevice *handle, int32_t value);

/**
 * Read current sensor gain into `*out_value`.
 */
int obsbot_device_gain(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set backlight compensation (PU). u16 LE; 0 disables it.
 */
int obsbot_device_set_backlight_compensation(struct ObsbotDevice *handle, int32_t value);

/**
 * Read current backlight-compensation value into `*out_value`.
 */
int obsbot_device_backlight_compensation(struct ObsbotDevice *handle, int32_t *out_value);

/**
 * Set anti-flicker mode (PU): 0 = Off, 1 = 50 Hz, 2 = 60 Hz, 3 = Auto.
 */
int obsbot_device_set_anti_flicker(struct ObsbotDevice *handle, int mode);

/**
 * Read current anti-flicker mode into `*out_mode` (same encoding).
 */
int obsbot_device_anti_flicker(struct ObsbotDevice *handle, int *out_mode);

/**
 * Enable or disable autofocus (CT).
 */
int obsbot_device_set_auto_focus(struct ObsbotDevice *handle, int on);

/**
 * Whether autofocus is currently enabled.
 */
int obsbot_device_auto_focus(struct ObsbotDevice *handle, int *out_on);

/**
 * Set auto-exposure mode: 0 = Manual, 1 = Auto, 2 = `ShutterPriority`,
 * 3 = `AperturePriority`.
 */
int obsbot_device_set_ae_mode(struct ObsbotDevice *handle, int mode);

/**
 * Read current auto-exposure mode into `*out_mode` (same encoding).
 */
int obsbot_device_ae_mode(struct ObsbotDevice *handle, int *out_mode);

/**
 * Lock or unlock auto-exposure. Convenience over
 * [`obsbot_device_set_ae_mode`].
 */
int obsbot_device_set_ae_lock(struct ObsbotDevice *handle, int locked);

/**
 * Set manual exposure time in 100 us units (CT).
 */
int obsbot_device_set_exposure_time(struct ObsbotDevice *handle, uint32_t value_100us);

/**
 * Read current exposure time (100 us units) into `*out_value`.
 */
int obsbot_device_exposure_time(struct ObsbotDevice *handle, uint32_t *out_value);

/**
 * Set pan + tilt as normalised values in -1.0..=1.0.
 */
int obsbot_device_set_pan_tilt(struct ObsbotDevice *handle, float pan, float tilt);

/**
 * Set zoom as a u16-clamped objective focal length.
 */
int obsbot_device_set_zoom(struct ObsbotDevice *handle, float zoom);

/**
 * Set focus as a u16-clamped distance value.
 */
int obsbot_device_set_focus(struct ObsbotDevice *handle, float focus);

/**
 * White-balance mode: 0 = Auto, 1 = Manual. `kelvin` is honoured only
 * for Manual; pass 0 with Auto.
 */
int obsbot_device_set_white_balance(struct ObsbotDevice *handle, int mode, uint16_t kelvin);

/**
 * HDR mode: 0 = Off, 1 = `Dol2To1`.
 */
int obsbot_device_set_wdr(struct ObsbotDevice *handle, int mode);

/**
 * Read current HDR mode into `*out_mode` (same encoding as
 * [`obsbot_device_set_wdr`]).
 */
int obsbot_device_wdr(struct ObsbotDevice *handle, int *out_mode);

/**
 * Read current face-AE state into `*out_on` (`0` = off, `1` = on).
 */
int obsbot_device_face_ae(struct ObsbotDevice *handle, int *out_on);

/**
 * Read current AI master mode into `*out_mode` (same encoding as
 * [`obsbot_device_set_ai_mode`]).
 */
int obsbot_device_ai_mode(struct ObsbotDevice *handle, int *out_mode);

/**
 * FOV preset: 0 = Wide, 1 = Medium, 2 = Narrow.
 */
int obsbot_device_set_fov(struct ObsbotDevice *handle, int fov);

/**
 * Face-AE toggle: non-zero on, zero off.
 */
int obsbot_device_set_face_ae(struct ObsbotDevice *handle, int on);

/**
 * Face-focus toggle: non-zero on, zero off.
 */
int obsbot_device_set_face_focus(struct ObsbotDevice *handle, int on);

/**
 * Media mode: 0 = Normal, 1 = Background, 2 = `AutoFrame`.
 */
int obsbot_device_set_media_mode(struct ObsbotDevice *handle, int mode);

/**
 * Auto-framing sub-mode: 0 = Group, 1 = `SingleCloseUp`, 2 = `SingleUpperBody`.
 */
int obsbot_device_set_auto_framing(struct ObsbotDevice *handle, int mode);

/**
 * AI master mode: 0 = None, 1 = Group, 2 = Human, 3 = Hand,
 * 4 = `WhiteBoard`, 5 = Desk.
 */
int obsbot_device_set_ai_mode(struct ObsbotDevice *handle, int mode);

/**
 * Microphone Automatic Gain Control: non-zero on, zero off.
 */
int obsbot_device_set_audio_agc(struct ObsbotDevice *handle, int on);

/**
 * Horizontal image flip (left/right mirror).
 */
int obsbot_device_set_flip_horizontal(struct ObsbotDevice *handle, int on);

/**
 * Switch between landscape (0) and portrait (non-zero) orientation.
 */
int obsbot_device_set_portrait(struct ObsbotDevice *handle, int on);

/**
 * Turn the front-facing status LED on (non-zero) or off (zero).
 */
int obsbot_device_set_led(struct ObsbotDevice *handle, int on);

/**
 * Master enable for the virtual-background system.
 */
int obsbot_device_set_bg_enable(struct ObsbotDevice *handle, int on);

/**
 * Virtual-background mode: 0 = Disable, 1 = Color, 17 = Replace, 18 = Blur.
 */
int obsbot_device_set_bg_mode(struct ObsbotDevice *handle, int mode);

/**
 * Background colour key: -2 = Disable, -1 = Null, 0 = Blue, 1 = Green,
 * 2 = Red, 3 = Black, 4 = White.
 */
int obsbot_device_set_bg_color(struct ObsbotDevice *handle, int color);

/**
 * Set the virtual-background blur intensity, 0..=100.
 */
int obsbot_device_set_mask_level(struct ObsbotDevice *handle, int level);

/**
 * Control auto-suspend without streaming. Non-zero disables sleep.
 */
int obsbot_device_set_disable_sleep_without_stream(struct ObsbotDevice *handle, int disable);

/**
 * Set the auto-suspend timer in minutes; `0` keeps the camera awake.
 */
int obsbot_device_set_suspend_time(struct ObsbotDevice *handle, uint16_t minutes);

/**
 * Status poller cadence: 0 = Slow (2.5 s), 1 = Fast (25 ms).
 */
int obsbot_device_set_status_cadence(struct ObsbotDevice *handle, int cadence);

/**
 * Read current white-balance mode + Kelvin value. `mode` follows the
 * same encoding as [`obsbot_device_set_white_balance`].
 */
int obsbot_device_white_balance(struct ObsbotDevice *handle, int *out_mode, uint16_t *out_kelvin);

/**
 * Read current pan + tilt as normalised values in -1.0..=1.0.
 */
int obsbot_device_pan_tilt(struct ObsbotDevice *handle, float *out_pan, float *out_tilt);

/**
 * Read current zoom value.
 */
int obsbot_device_zoom(struct ObsbotDevice *handle, float *out);

/**
 * Read current focus value.
 */
int obsbot_device_focus(struct ObsbotDevice *handle, float *out);

/**
 * Read a synchronous status snapshot into `*out`. Returns
 * `OBSBOT_ERR_NOT_FOUND` for NULL handles. Best-effort: individual
 * read failures leave the corresponding field at its default value
 * rather than failing the whole call.
 */
int obsbot_device_status(struct ObsbotDevice *handle, struct ObsbotStatus *out);

/**
 * Read the camera-reported firmware version into `out_buf` as a
 * NUL-terminated string. `buf_len` must include space for the NUL.
 * Returns `OBSBOT_ERR_OUT_OF_RANGE` if the buffer is too small.
 */
int obsbot_device_firmware(struct ObsbotDevice *handle, char *out_buf, uintptr_t buf_len);

/**
 * Read the camera-reported serial number into `out_buf` as a
 * NUL-terminated string. Same buffer-size contract as
 * [`obsbot_device_firmware`].
 */
int obsbot_device_serial(struct ObsbotDevice *handle, char *out_buf, uintptr_t buf_len);

/**
 * Return the libobsbot version string (NUL-terminated, static lifetime).
 */
const char *obsbot_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
