/* SPDX-License-Identifier: GPL-3.0-only */
/* libobsbot - clean-room cross-platform OBSBOT camera SDK
 * Generated by cbindgen. Do not edit by hand. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define OBSBOT_OK 0

/**
 * Generic / USB error.
 */
#define OBSBOT_ERR_USB -1

/**
 * No matching device.
 */
#define OBSBOT_ERR_NOT_FOUND -2

/**
 * Timeout while waiting for a camera response.
 */
#define OBSBOT_ERR_TIMEOUT -3

/**
 * Operation unsupported on this platform or device.
 */
#define OBSBOT_ERR_UNSUPPORTED -4

/**
 * Argument out of accepted range.
 */
#define OBSBOT_ERR_OUT_OF_RANGE -5

/**
 * Camera firmware too old.
 */
#define OBSBOT_ERR_FIRMWARE -6

/**
 * Camera returned a malformed response.
 */
#define OBSBOT_ERR_BAD_RESPONSE -7

/**
 * Opaque handle to an opened OBSBOT camera.
 */
typedef struct ObsbotDevice ObsbotDevice;

/**
 * Opaque handle to the hot-plug watcher / device registry.
 */
typedef struct ObsbotDevices ObsbotDevices;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new `ObsbotDevices` registry. Returns NULL on failure.
 */
struct ObsbotDevices *obsbot_devices_new(void);

/**
 * Free an `ObsbotDevices` registry previously returned by
 * [`obsbot_devices_new`]. Passing NULL is a no-op.
 */
void obsbot_devices_free(struct ObsbotDevices *handle);

/**
 * Number of OBSBOT cameras currently connected.
 */
int obsbot_devices_count(struct ObsbotDevices *handle);

/**
 * Open the first connected OBSBOT camera. Writes the resulting handle to
 * `*out_device`. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_devices_open_first(struct ObsbotDevices *handle, struct ObsbotDevice **out_device);

/**
 * Free an `ObsbotDevice` previously returned by [`obsbot_devices_open_first`].
 * Passing NULL is a no-op.
 */
void obsbot_device_close(struct ObsbotDevice *handle);

/**
 * Set camera brightness. Returns one of the `OBSBOT_*` codes.
 */
int obsbot_device_set_brightness(struct ObsbotDevice *handle, int32_t value);

/**
 * Return the libobsbot version string (NUL-terminated, static lifetime).
 */
const char *obsbot_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
